name: Feature Request
description: "Suggest a new feature for typed_configparser"
labels: [feature request]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to typed_configparser!

  - type: checkboxes
    id: searched
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a feature request.
      options:
        - label: I have searched Google & GitHub for similar requests and couldn't find anything
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest.

        You might like to add:
        * A demo of how code might look when using the feature
        * Your use case(s) for the feature
    validations:
      required: true
